In [1]:
import os
import pandas as pd
from collections import defaultdict

In [2]:
# Define the paths to your positive and negative data folders
origin_path = "D:/OneDrive - Indian Institute of Technology Bombay/Study/Semester 5/CS 626/Project/review_polarity/"
positive_folder = origin_path + "txt_sentoken/pos"
negative_folder = origin_path + "txt_sentoken/neg"

In [8]:
# Initialize empty lists to store data
reviews = []
labels = []

# Read positive sentiment reviews
for filename in os.listdir(positive_folder):
    with open(os.path.join(positive_folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        labels.append('positive')

# Read negative sentiment reviews
for filename in os.listdir(negative_folder):
    with open(os.path.join(negative_folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        labels.append('negative')

# Create a DataFrame
panglee = pd.DataFrame({'Review': reviews, 'Label': labels})
panglee[["len"]]  = panglee[["Review"]].applymap(len)
panglee.to_csv("./data/panglee_sup.csv")
panglee

                                                 Review     Label   len
0     films adapted from comic books have had plenty...  positive  4227
1     every now and then a movie comes along from a ...  positive  4096
2     you've got mail works alot better than it dese...  positive  2421
3      " jaws " is a rare film that grabs your atten...  positive  6092
4     moviemaking is a lot like being the general ma...  positive  3898
...                                                 ...       ...   ...
1995  if anything , " stigmata " should be taken as ...  negative  8356
1996  john boorman's " zardoz " is a goofy cinematic...  negative  6211
1997  the kids in the hall are an acquired taste . \...  negative  2342
1998  there was a time when john carpenter was a gre...  negative  3183
1999  two party guys bob their heads to haddaway's d...  negative  3255

[2000 rows x 3 columns]

In [30]:
# Your list of numbers
panglee_len = list(panglee["len"])

# Define the range size (e.g., 1000)
range_size = 1000

# Create a defaultdict to count frequencies in ranges
frequency_distribution = defaultdict(int)

# Count frequencies in ranges
for number in panglee_len:
    range_start = (number // range_size) * range_size
    range_end = range_start + range_size
    range_label = f"{range_start}-{range_end}"
    frequency_distribution[range_label] += 1

# Display the frequency distribution
for range_label, frequency in frequency_distribution.items():
    print(f"Range: {range_label}, Frequency: {frequency}")

Range: 4000-5000, Frequency: 415
Range: 2000-3000, Frequency: 427
Range: 6000-7000, Frequency: 95
Range: 3000-4000, Frequency: 545
Range: 5000-6000, Frequency: 197
Range: 1000-2000, Frequency: 200
Range: 7000-8000, Frequency: 50
Range: 0-1000, Frequency: 12
Range: 8000-9000, Frequency: 30
Range: 10000-11000, Frequency: 10
Range: 9000-10000, Frequency: 14
Range: 14000-15000, Frequency: 1
Range: 13000-14000, Frequency: 1
Range: 11000-12000, Frequency: 2
Range: 12000-13000, Frequency: 1

In [12]:
origin_path = "D:/OneDrive - Indian Institute of Technology Bombay/Study/Semester 5/CS 626/Project/aclImdb_v1/aclImdb/"
positive_folder = origin_path + "train/pos"
negative_folder = origin_path + "train/neg"

# Initialize empty lists to store data
reviews = []
labels = []

# Read positive sentiment reviews
for filename in os.listdir(positive_folder):
    with open(os.path.join(positive_folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        st = filename.index("_")
        en = filename.index(".")
        labels.append(filename[st+1:en])

# Read negative sentiment reviews
for filename in os.listdir(negative_folder):
    with open(os.path.join(negative_folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        st = filename.index("_")
        en = filename.index(".")
        labels.append(filename[st+1:en])

# Create a DataFrame
imdb_train = pd.DataFrame({'Review': reviews, 'Label': list(labels)})
imdb_train[["len"]]  = imdb_train[["Review"]].applymap(len)
imdb_train.to_csv("./data/imdb_train_sup.csv")
imdb_train

                                                  Review Label   len
0      Bromwell High is a cartoon comedy. It ran at t...     9   806
1      Homelessness (or Houselessness as George Carli...     8  2366
2      Brilliant over-acting by Lesley Ann Warren. Be...    10   841
3      This is easily the most underrated film inn th...     7   663
4      This is not the typical Mel Brooks film. It wa...     8   647
...                                                  ...   ...   ...
24995  Towards the end of the movie, I felt it was to...     4  1567
24996  This is the kind of movie that my enemies cont...     3   859
24997  I saw 'Descent' last night at the Stockholm Fi...     3  1688
24998  Some films that you pick up for a pound turn o...     1  1277
24999  This is one of the dumbest films, I've ever se...     1   746

[25000 rows x 3 columns]

In [32]:
# Your list of numbers
imdb_train_len = list(imdb_train["len"])

# Define the range size (e.g., 1000)
range_size = 1000

# Create a defaultdict to count frequencies in ranges
frequency_distribution = defaultdict(int)

# Count frequencies in ranges
for number in imdb_train_len:
    range_start = (number // range_size) * range_size
    range_end = range_start + range_size
    range_label = f"{range_start}-{range_end}"
    frequency_distribution[range_label] += 1

# Display the frequency distribution
for range_label, frequency in frequency_distribution.items():
    print(f"Range: {range_label}, Frequency: {frequency}")

Range: 0-1000, Frequency: 12851
Range: 2000-3000, Frequency: 2507
Range: 1000-2000, Frequency: 7825
Range: 3000-4000, Frequency: 1026
Range: 5000-6000, Frequency: 270
Range: 10000-11000, Frequency: 2
Range: 4000-5000, Frequency: 478
Range: 6000-7000, Frequency: 26
Range: 7000-8000, Frequency: 8
Range: 13000-14000, Frequency: 1
Range: 9000-10000, Frequency: 2
Range: 8000-9000, Frequency: 4

In [13]:
origin_path = "D:/OneDrive - Indian Institute of Technology Bombay/Study/Semester 5/CS 626/Project/aclImdb_v1/aclImdb/"
positive_folder = origin_path + "test/pos"
negative_folder = origin_path + "test/neg"

# Initialize empty lists to store data
reviews = []
labels = []

# Read positive sentiment reviews
for filename in os.listdir(positive_folder):
    with open(os.path.join(positive_folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        st = filename.index("_")
        en = filename.index(".")
        labels.append(filename[st+1:en])

# Read negative sentiment reviews
for filename in os.listdir(negative_folder):
    with open(os.path.join(negative_folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        st = filename.index("_")
        en = filename.index(".")
        labels.append(filename[st+1:en])

# Create a DataFrame
imdb_test = pd.DataFrame({'Review': reviews, 'Label': labels})
imdb_test[["len"]]  = imdb_test[["Review"]].applymap(len)
imdb_test.to_csv("./data/imdb_test_sup.csv")
imdb_test

                                                  Review Label   len
0      I went and saw this movie last night after bei...    10   794
1      Actor turned director Bill Paxton follows up h...     7  2004
2      As a recreational golfer with some knowledge o...     9  1434
3      I saw this film in a sneak preview, and it is ...     8   682
4      Bill Paxton has taken the true story of the 19...     8  1216
...                                                  ...   ...   ...
24995  I occasionally let my kids watch this garbage ...     1   645
24996  When all we have anymore is pretty much realit...     1   877
24997  The basic genre is a thriller intercut with an...     3  1623
24998  Four things intrigued me as to this film - fir...     3   749
24999  David Bryce's comments nearby are exceptionall...     4  2284

[25000 rows x 3 columns]

In [34]:
# Your list of numbers
imdb_test_len = list(imdb_test["len"])

# Define the range size (e.g., 1000)
range_size = 1000

# Create a defaultdict to count frequencies in ranges
frequency_distribution = defaultdict(int)

# Count frequencies in ranges
for number in imdb_test_len:
    range_start = (number // range_size) * range_size
    range_end = range_start + range_size
    range_label = f"{range_start}-{range_end}"
    frequency_distribution[range_label] += 1

# Display the frequency distribution
for range_label, frequency in frequency_distribution.items():
    print(f"Range: {range_label}, Frequency: {frequency}")

Range: 0-1000, Frequency: 12851
Range: 2000-3000, Frequency: 2507
Range: 1000-2000, Frequency: 7825
Range: 3000-4000, Frequency: 1026
Range: 5000-6000, Frequency: 270
Range: 10000-11000, Frequency: 2
Range: 4000-5000, Frequency: 478
Range: 6000-7000, Frequency: 26
Range: 7000-8000, Frequency: 8
Range: 13000-14000, Frequency: 1
Range: 9000-10000, Frequency: 2
Range: 8000-9000, Frequency: 4

In [14]:
origin_path = "D:/OneDrive - Indian Institute of Technology Bombay/Study/Semester 5/CS 626/Project/aclImdb_v1/aclImdb/"
folder = origin_path + "train/unsup"

# Initialize empty lists to store data
reviews = []
labels = []


# Read unsupervised reviews
for filename in os.listdir(folder):
    with open(os.path.join(folder, filename), 'r', encoding='utf-8') as file:
        review = file.read()
        reviews.append(review)
        labels.append('unsupervised')

# Create a DataFrame
imdb_unsup = pd.DataFrame({'Review': reviews, 'Label': labels})
imdb_unsup[["len"]]  = imdb_test[["Review"]].applymap(len)
imdb_unsup.to_csv("./data/imdb_train_unsup.csv")
imdb_unsup

                                                  Review         Label     len
0      I admit, the great majority of films released ...  unsupervised   794.0
1      Take a low budget, inexperienced actors doubli...  unsupervised  2004.0
2      Everybody has seen 'Back To The Future,' right...  unsupervised  1434.0
3      Doris Day was an icon of beauty in singing and...  unsupervised   682.0
4      After a series of silly, fun-loving movies, 19...  unsupervised  1216.0
...                                                  ...           ...     ...
49995  Delightfully awful! Made by David Giancola, a ...  unsupervised     NaN
49996  Watching Time Chasers, it obvious that it was ...  unsupervised     NaN
49997  At the beginning we can see members of Troma t...  unsupervised     NaN
49998  The movie was incredible, ever since I saw it ...  unsupervised     NaN
49999  TCM came through by acquiring this wonderful, ...  unsupervised     NaN

[50000 rows x 3 columns]